# fly.toml app configuration file generated for tapi-ai-server on 2024-12-23T08:12:39-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tapi-ai-server'
primary_region = 'eze'

[build]


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[env]
  HOSTNAME = "0.0.0.0"

[[services]]
  internal_port = 3000 # Puerto que usa tu aplicación
  protocol = "tcp"
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    interval = "10s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "2s"
    tls_skip_verify = false

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
